import { StyleSheet, Text, View } from "react-native";
import { Colors } from "../../Utils/ReUsables";

export const NewCompScreenStyle = StyleSheet.create({
  Container: {},
  Image: {
    height: 160,
    width: null,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    padding: 10,
    paddingTop: 60,
  },
  InfoContainer: {
    height: 45,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: Colors.Dirty_White,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  IngredientsContainer: {
    marginVertical: 20,
    justifyContent: "flex-start",
    flexWrap: "wrap",
    flexDirection: "row",
    marginBottom: 20,
  },
  InputContainer: {
    alignItems: "center",
    flexDirection: "column",
    padding: 20,
    justifyContent: "space-between",
  },
  IngredientView: {
    margin: 2,
    padding: 10,
    paddingLeft: 15,
    paddingRight: 15,
    backgroundColor: Colors.LightGreen,
    borderRadius: 20,
    justifyContent: "center",
  },
  addImage: {
    width: 300,
    backgroundColor: Colors.Dirty_White_Darker,
    alignSelf: "center",
    height: 150,
    resizeMode: "center",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 15,
    marginBottom: 20,
  },
  hide: {
    display: "none",
  },
  addImageInner: {
    marginBottom: 20,
    width: 40,
    height: 40,
    opacity: 0.5,
  },
  StepsContainer: {
    marginVertical: 20,
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
    flexDirection: "column",
    marginBottom: 20,
  },
  StepsView: {
    width: "100%",
    margin: 2,
    paddingLeft: 15,
    paddingRight: 15,
    padding: 10,
    backgroundColor: Colors.LightRed,
    borderRadius: 20,
    justifyContent: "center",
  },
});
